### ISSUE TITLE
Nukes fired at max range with occular implants fail to drop in OpenBW (causes desync in replay viewer if game was played in normal Brood War)

### ISSUE THREAD

**Issue by N00byEdge** [OpenBW/openbw#2]
Attaching a couple of replay files where the desync happens
[Desync_replays.zip](https://github.com/OpenBW/openbw/files/1292472/Desync_replays.zip)

**Comment by N00byEdge** [comment]
It should be noted that the games play out fine in the game (with RepFix), without desyncs.

**Comment by tscmoo** [comment]
Sorry this took a while to fix (you reported it long before creating this issue). If you notice any other desyncs, then please create a new issue, thanks.

**Comment by N00byEdge** [comment]
No problem. Thanks a lot for fixing this. I'm sure this means a lot to me and a lot of other people.

**Comment by N00byEdge** [comment]
Now that I've had time to test this. It sure looks like a lot more nukes are being dropped but there are still desyncs in those replays. Or hasn't the replay viewer been updated yet?

**Comment by tscmoo** [comment]
It's updated, but you may have had an old version cached. Check that it says v26 in the console (f12), ctrl+f5 to refresh if necessary.

**Comment by N00byEdge** [comment]
Oh yeah it works, nevermind then. I'll keep you posted if I find anything else.
