### ISSUE TITLE
Fail to launch exampleAIModule

### ISSUE THREAD

**Issue by guileen** [OpenBW/openbw#5]
I compiled project on OS X, put Patch_rt.mpq, BroodDat.mpq, StarDat.mpq in working directory, but I got `Error: file_reader: failed to open  for reading`

https://github.com/OpenBW/bwapi/blob/3926e90f4f2f6eef271fdaddd6bf176a4e50e55e/bwapi/OpenBWData/BW/BWData.cpp#L482

The `filename` is Empty.

**Comment by N00byEdge** [comment]
That's when you're missing `bwapi.ini` n the `bwapi-data` directory. I agree this error should look better.

**Comment by guileen** [comment]
I think it would be very helpful to give step by step of run ExampleAIMoudle  in README.md. 

I spent week to work with original Starcraft and  BWAPI on OS X, and finally give up. I wish OpenBW could be the classic platform to play AI.

**Comment by guileen** [comment]
I have copy `bwapi.ini` into `bwapi-data` and run 

`BWAPI_CONFIG_AI__AI=./lib/ExampleAIModule.dylib BWAPI_CONFIG_AUTO_MENU__RACE=Zerg ./bin/BWAPILauncher`

in the build folder, but it got stuck at [this line](https://github.com/OpenBW/bwapi/blob/develop-openbw/bwapi/BWAPI/Source/BWAPI/AutoMenuManager.cpp#L314) , just loop for ever.

**Comment by guileen** [comment]
I change `auto_menu = OFF` to `auto_menu=SINGLE_PLAYER` then it works, but only a single AI
 vs an not playable player.

I wonder how to let two AI fight each other.

**Comment by guileen** [comment]
Got it, just run two instance with multiplay game.
