### ISSUE TITLE
How to draw text on screen? Broodwar->drawTextScreen and Broodwar->sendText not works as I expected.

### ISSUE THREAD

**Issue by guileen** [OpenBW/openbw#9]
I wish to draw text on screen, and send log on screen, but it not works with `Broodwar->drawTextScreen` and `Broodwar->sendText`, but `Broodwar->drawCircleScreen` and `Broodwar->drawBoxMap` works well.

Test with ExampleAIModule on https://github.com/OpenBW/openbw/commit/3b75e9f684b9e2ed63c2697811828a887c28803c and https://github.com/OpenBW/bwapi/commit/32943f016a37468c381894d5a178a121e9668907.

**Comment by tscmoo** [comment]
Text is unfortunately not supported yet :(
It should be added sometime soon.

**Comment by tscmoo** [comment]
Well, I *finally* merged your pr openbw/bwapi#2, so it should work now, right? :)
